export const INIT = 'INIT'

export const FETCH_USERS = 'FETCH_USERS'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR'

export const FETCH_MESSAGES = 'FETCH_MESSAGES'
export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS'
export const FETCH_MESSAGES_ERROR = 'FETCH_MESSAGES_ERROR'

export const CREATE_MESSAGE = 'CREATE_MESSAGE'

export const SEND_MESSAGE = 'SEND_MESSAGE'
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS'
export const SEND_MESSAGE_ERROR = 'SEND_MESSAGE_ERROR'

export const TYPING_MESSAGE = 'TYPING_MESSAGE'
export const TYPING_MESSAGE_SUCCESS = 'TYPING_MESSAGE_SUCCESS'
export const TYPING_MESSAGE_ERROR = 'TYPING_MESSAGE_ERROR'